export const SERVICE = {
  NAME: 'SUBSCRIBERS_SERVICE',
  HOST: 'SERVICE_HOST_SUBSCRIBERS',
  PORT: 'SERVICE_PORT_SUBSCRIBERS'
};

export const SERVICE_COMMANDS = {
  ADD_SUBSCRIBER: 'add-subscriber',
  GET_ALL_SUBSCRIBERS: 'get-all-subscribers',
};
