version: '3'
services:
  postgres:
    container_name: postgres-nest-tut
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres-nest-tut
    
  pgadmin:
    links:
      - postgres:postgres-nest-tut
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres-nest-tut

networks:
  postgres-nest-tut:
    driver: bridge
