const JWT_AT_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
const JWT_AT_EXP = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME';
const JWT_RT_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
const JWT_RT_EXP = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME';

export {
  JWT_AT_SECRET,
  JWT_AT_EXP,
  JWT_RT_SECRET,
  JWT_RT_EXP,
}
